
if 1
  inPath = fullfile(vtData, '0627MUSICPIG');
  inFilePrePre = 'FUS_pig_afterkataminepreFUS20240627_194601_sdl_s1_sg';
  inFilePre = [inFilePrePre]; 
  sgSel = [1:6];
  % indices in matrix to average over to get Doppler signal
  % generated by running offlinesdlarge, or otherwise
  topInd = [418] %   421   380   419   379   420   377   378];  
end

if 0
  inPath = fullfile(vtData, '06272024MUSIC');
  inFilePrePre = 'PostPostFUS20240627_200144_sdl_s1_sg';
  inFilePre = [inFilePrePre]; 
  sgSel = [1:14];
  % indices in matrix to average over to get Doppler signal
  % generated by running offlinesdlarge, or otherwise
  topInd = [ 423   379   384   422   383   382   380   381];
end


if 0
  inPath = fullfile(vtData, '20240718');
  inFilePrePre = 'PostFUS20240718_170124_sdl_s2_sg';
  inFilePre = [inFilePrePre]; 
  sgSel = [1:9];
  % indices in matrix to average over to get Doppler signal
  % generated by running offlinesdlarge, or otherwise
  topInd = [232   188   231   268   229   108   150   189];
end


if 0
  inPath = fullfile(vtData, '20240718');
  inFilePrePre = 'PreFUS20240718_165558_sdl_s1_sg';
  inFilePre = [inFilePrePre]; 
  sgSel = [1:6];
  % indices in matrix to average over to get Doppler signal
  % generated by running offlinesdlarge, or otherwise
  topInd = [308   264   191   226   306   228   265   227];
  topInd = [264 265]; % manually chosen
  topInd = [262   266   263   225   264   226   265   227]; % linear feature
end

if 1
  inPath = fullfile(vtData, '20240718');
  inFilePrePre = 'PostFUS20240718_170124_sdl_s2_sg';
  inFilePre = [inFilePrePre]; 
  sgSel = [1:9];
  % indices in matrix to average over to get Doppler signal
  % generated by running offlinesdlarge, or otherwise
  %  topInd = [232   188   231   268   229   108   150   189];
  % sd size is 40x20
  topInd = [  101   142   143   103   141    99   145   104];
  
end

if 0
  inPath = fullfile(vtData, '20240729');
  inFilePrePre = 'FUS1pre20240729_162348_sdl_s1_sg'; % nice, clear
  inFilePre = [inFilePrePre]; 
  sgSel = [1]; 
  topInd = [340   426   385   342   382   384   341   383];
end


if 0
  inPath = fullfile(vtData, '20240729');
  inFilePrePre = 'FUS1pre(opt)20240729_162443_sdl_s2_sg'; % nice, clear
  inFilePre = [inFilePrePre]; 
  sgSel = [1:27]; 
  topInd = [ 382   421   379   424   422   423   380   381];
end

if 0
  inPath = fullfile(vtData, '20240729');
  inFilePrePre = 'FUS1post20240729_163730_sdl_s3_sg'; % good
  inFilePre = [inFilePrePre]; 
  sgSel = [1:15]; 
  topInd = [  341   423   340   424   425   383   382   381];
end


if 0
  inPath = fullfile(vtData, '20240729');
  inFilePrePre = 'FUS2post20240729_164533_sdl_s4_sg'; % good
  inFilePre = [inFilePrePre]; 
  sgSel = [1:15]; 
  topInd = [466   425   382   422   424   423   380   381];

end

if 0
  inPath = fullfile(vtData, '20240729');
  inFilePrePre = 'FUS3post20240729_165341_sdl_s5_sg'; % good
  inFilePre = [inFilePrePre]; 
  sgSel = [1:14]; 
  %sgSel = [1];
  % restrict search for max flow pixels to area with vessel
  topInd = [299   298   384   382   383   339   341   340];
end

if 0
  inPath = fullfile(vtData, '20240729');
  inFilePrePre = 'FUS4post20240729_170139_sdl_s6_sg';
  inFilePre = [inFilePrePre]; 
  sgSel = [1:26]; 
  %sgSel = [1];
  % restrict search for max flow pixels to area with vessel
  topInd = [426   425   384   381   341   340   382   383];
end


